# Generated by Django 2.2.7 on 2019-11-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appizza', '0002_auto_20191118_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='appizza.Ingrediente'),
        ),
    ]
