# Generated by Django 2.2.7 on 2019-11-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appizza', '0004_pizza_tamano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='Tamano',
        ),
        migrations.AddField(
            model_name='pizza',
            name='Tamano',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
