# Generated by Django 2.2.7 on 2019-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appizza', '0005_auto_20191118_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='appizza.Ingrediente'),
        ),
    ]
