# Generated by Django 2.2.6 on 2019-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appizza', '0006_auto_20191120_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='Tamano',
            new_name='tamano',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(related_name='ingredientes', to='appizza.Ingrediente'),
        ),
    ]
